part 1

#Load the Dataset
#Load the dataset from the CSV file into a Pandas DataFrame.
#Display the first 5 and last 10 rows of the data


In [ ]:

import pandas as pd
file_path = '/content/sample_data/california_housing_train.csv'
df = pd.read_csv(file_path)
df.head(5)  #print first five rows of data


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [ ]:
df.tail(10)   #print  last 10 rows of data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

**## Data Summary**
1)Get a statistical summary of the dataset to examine the numerical columns.
2)Identify the unique values in the total_bedrooms column and determine how many distinct values it has
*italicized text*

In [ ]:
#Get a statistical summary of the dataset to examine the numerical columns.

df.describe()


longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
#Identify the unique values in the total_bedrooms column and determine how many distinct values it has

unique_values = df['total_bedrooms'].unique()
distinct_count = df['total_bedrooms'].nunique()
unique_values, distinct_count


(array([1283., 1901.,  174., ..., 1637., 1308.,  936.]), 1848)

Data Transformation

In [ ]:
#Add a new column to the DataFrame named total_bedrooms_per_total_rooms, calculated as total_bedrooms / total_rooms.

df['total_bedrooms_per_total_rooms'] = df['total_bedrooms'] / df['total_rooms']
df.head()


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  \
0      1015.0       472.0         1.4936             66900.0   
1      1129.0       463.0         1.8200             80100.0   
2       333.0       117.0         1.6509             85700.0   
3       515.0       226.0         3.1917             73400.0   
4       624.0       262.0         1.9250             65500.0   

   total_bedrooms_per_total_rooms  
0                        0.228617  
1                        0.248497  
2                        0.241667  
3                        0.224517  
4                        0.224209

In [ ]:
#Compute the mean and standard deviation of the new column (total_bedrooms_per_total_rooms) and report these values

mean_value = df['total_bedrooms_per_total_rooms'].mean()
std_dev_value = df['total_bedrooms_per_total_rooms'].std()
mean_value, std_dev_value


(0.21275998821034803, 0.057823008903161756)

Data Filtering

In [ ]:
#Filter the dataset to find rows where the median_income is greater than 5

filtered_df = df[df['median_income'] > 5]
filtered_df.head()


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32     -115.39     32.76                16.0       1136.0           196.0   
69     -115.55     32.98                33.0       2266.0           365.0   
92     -115.57     32.78                20.0       1534.0           235.0   
98     -115.58     32.78                 5.0       2494.0           414.0   
100    -115.59     32.79                 8.0       2183.0           307.0   

     population  households  median_income  median_house_value  \
32        481.0       185.0         6.2558            146300.0   
69        952.0       360.0         5.4349            143000.0   
92        871.0       222.0         6.2715             97200.0   
98       1416.0       421.0         5.7843            110100.0   
100      1000.0       287.0         6.3814            159900.0   

     total_bedrooms_per_total_rooms  
32                         0.172535  
69                         0.161077  
92                         0.153194  
98                         0.165998  
100                        0.140632

In [ ]:
#Create a subset of the data where the number of rooms (total_rooms) exceeds 10,000 and the median_house_value is below $150,000. Display this filtered subset


subset_df = df[(df['total_rooms'] > 10000) & (df['median_house_value'] < 150000)]
subset_df.head()


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133    -116.06     34.15                15.0      10377.0          2331.0   
191    -116.36     33.88                11.0      12557.0          3098.0   
198    -116.38     33.73                10.0      11836.0          2405.0   
201    -116.39     33.82                15.0      11115.0          2257.0   
229    -116.47     33.81                 7.0      10105.0          2481.0   

     population  households  median_income  median_house_value  \
133      4507.0      1807.0         2.2466             66800.0   
191      2453.0      1232.0         1.7844             78500.0   
198      3811.0      1570.0         4.0079            134500.0   
201      4122.0      1653.0         2.7219             74400.0   
229      6274.0      2095.0         2.4497             90900.0   

     total_bedrooms_per_total_rooms  
133                        0.224631  
191                        0.246715  
198                        0.203194  
201                        0.203059  
229                        0.245522

Export Modified Data

In [ ]:
#Save the modified DataFrame (after adding the extra column) to a new CSV file

df.to_csv('/content/sample_data/modified_california_housing.csv', index=False)



***Part 2: Numerical Analysis with NumPy (30 Points)bold ***



Array Creation and Indexing

In [ ]:
#Create a 1D NumPy array of integers from 1 to 20

import numpy as np
array = np.arange(1, 21)
array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#Extract the even numbers from this array using slicing.

even_numbers = array[1::2]
even_numbers


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100

random_array = np.random.randint(10, 101, size=(5, 4))
random_array


array([[78, 50, 91, 68],
       [57, 67, 58, 11],
       [18, 69, 24, 31],
       [10, 74, 20, 72],
       [59, 59, 27, 75]])

In [ ]:
#Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).

subarray = random_array[:3, :2]
subarray



array([[78, 50],
       [57, 67],
       [18, 69]])

Array Manipulation

In [ ]:
#Reshape the 1D array of integers into a 4x5 2D array

reshaped_array = array[:20].reshape(4, 5)
reshaped_array


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
#Flatten the 2D array back to a 1D array and print it.

flattened_array = reshaped_array.flatten()
flattened_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).

import numpy as np
matrix_A = np.random.randint(1, 10, size=(3, 4))
matrix_B = np.random.randint(1, 10, size=(4, 5))
result_matrix = np.dot(matrix_A, matrix_B)
result_matrix


array([[ 32, 112, 110, 136,  62],
       [ 40,  97, 113, 115,  80],
       [ 79, 200, 227, 247, 130]])

Boolean and Fancy Indexing

In [ ]:
#Create a NumPy array of 50 random integers between 0 and 100.

import numpy as np
random_array = np.random.randint(0, 101, size=50)
random_array


array([71, 90, 44, 13,  1, 10, 26, 58, 94,  1, 26, 48, 17, 91, 99, 53, 49,
       91,  7, 40, 37, 20, 74,  5, 14, 22, 13, 51, 68, 39,  9, 22, 10,  2,
       32, 80, 68, 86, 94, 31, 46, 65, 34,  9, 83, 94, 12, 36, 44, 74])

In [ ]:
#Use Boolean indexing to extract all values greater than 50 from the array.

values_greater_than_50 = random_array[random_array > 50]
values_greater_than_50


array([71, 90, 58, 94, 91, 99, 53, 91, 74, 51, 68, 80, 68, 86, 94, 65, 83,
       94, 74])

In [ ]:
#Use fancy indexing to extract elements from the array at specific indices

indices = [3, 7, 10, 15, 20]
extracted_elements = random_array[indices]
extracted_elements


array([13, 58, 26, 53, 37])

Statistical Operations

In [ ]:
#For the 2D array created earlier, calculate the mean, max, and sum along each column.

mean_values = random_array.mean(axis=0)

max_values = random_array.max(axis=0)

sum_values = random_array.sum(axis=0)
mean_values, max_values, sum_values


(44.06, 99, 2203)

In [ ]:
#Create a mask to select elements that are greater than the mean value for each column and apply the mask to filter the array

mean_values = random_array.mean(axis=0)
mask = random_array > mean_values
filtered_array = random_array[mask]
filtered_array


array([71, 90, 58, 94, 48, 91, 99, 53, 49, 91, 74, 51, 68, 80, 68, 86, 94,
       46, 65, 83, 94, 74])

***Part 3: Problem Solving with Python Basics (20 Points)***

Loops and Conditional Statements

In [ ]:
#Print the Fibonacci sequence up to 100 using a loop.

a, b = 0, 1
while a <= 100:
    print(a, end=' ')
    a, b = b, a + b


0 1 1 2 3 5 8 13 21 34 55 89 

In [ ]:
#Loop through the numbers from 1 to 50 and print:
#"Fizz" for multiples of 3.
#"Buzz" for multiples of 5.
#"FizzBuzz" for multiples of both 3 and 5


for i in range(1, 51):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


Variable-Length Arguments

In [ ]:
#Write a solution that accepts a list of numbers and returns the median value

def find_median(numbers):
    # Sort the list first
    numbers.sort()

    n = len(numbers)

    if n % 2 == 1:
        return numbers[n // 2]
    else:
        middle1 = numbers[n // 2 - 1]
        middle2 = numbers[n // 2]
        return (middle1 + middle2) / 2

numbers = [12, 3, 5, 7, 19, 2]  #example
median = find_median(numbers)
print("The median is:", median)


The median is: 6.0


In [ ]:
#Write a solution that accepts a variable number of arguments and returns the average of the numbers.

def calculate_average(*args):
    if len(args) == 0:
        return None

    return sum(args) / len(args)
average = calculate_average(10, 20, 30, 40, 50)
print("The average is:", average)


The average is: 30.0


Error Handling

In [ ]:
#Handle the case where a division by zero occurs and print an appropriate error message

def calculate_average(*args):
    if len(args) == 0:
        print("Error: No numbers provided. Cannot calculate average.")
        return None

    return sum(args) / len(args)

average = calculate_average(10, 20, 30, 40, 50)
if average is not None:
    print("The average is:", average)

average = calculate_average()


The average is: 30.0
Error: No numbers provided. Cannot calculate average.


**Part 4: Bonus Challenge (Optional) (20 Points)**

Advanced NumPy Manipulation

In [ ]:
#Create a 3D NumPy array with specific dimensions and populate it with random numbers.

import numpy as np

random_3d_array = np.random.rand(3, 4, 5)
print(random_3d_array)




[[[0.56844882 0.47286966 0.43819208 0.49454255 0.73183503]
  [0.75755215 0.31738868 0.83405792 0.48497247 0.89921165]
  [0.62691832 0.00754023 0.03345785 0.27441084 0.97555748]
  [0.10252377 0.61181629 0.25497989 0.94634123 0.78188962]]

 [[0.08670249 0.31511045 0.39323029 0.89339818 0.9127958 ]
  [0.97129977 0.80365287 0.22554807 0.58201314 0.36458437]
  [0.38029609 0.23758345 0.88593322 0.05511828 0.41940659]
  [0.67420883 0.02041959 0.15237095 0.08641957 0.4869359 ]]

 [[0.5796967  0.13526612 0.39499318 0.07899675 0.76089596]
  [0.79912834 0.68927076 0.42117758 0.52684654 0.70561814]
  [0.09272314 0.68891895 0.75211216 0.09561575 0.6174981 ]
  [0.69084036 0.5093054  0.16630592 0.30043269 0.61338882]]]


In [ ]:
#Swap two of its axes.

import numpy as np
random_3d_array = np.random.randint(0, 101, size=(3, 4, 5))
print("Original 3D Array (Shape: {}):".format(random_3d_array.shape))
print(random_3d_array)

swapped_array = np.swapaxes(random_3d_array, 0, 1)

print("\nSwapped Array (Shape: {}):".format(swapped_array.shape))
print(swapped_array)


Original 3D Array (Shape: (3, 4, 5)):
[[[ 6 94 20 64 77]
  [93  5 55 14 52]
  [19 55 13  8 42]
  [22 32 20 61 54]]

 [[81 26 80 70  9]
  [18  9 97 66 84]
  [49 65 68 22 31]
  [ 6 50 25 40  9]]

 [[77 54 53 64 66]
  [99 76 98 65 50]
  [19 18 24 73 27]
  [26 32 60 47 72]]]

Swapped Array (Shape: (4, 3, 5)):
[[[ 6 94 20 64 77]
  [81 26 80 70  9]
  [77 54 53 64 66]]

 [[93  5 55 14 52]
  [18  9 97 66 84]
  [99 76 98 65 50]]

 [[19 55 13  8 42]
  [49 65 68 22 31]
  [19 18 24 73 27]]

 [[22 32 20 61 54]
  [ 6 50 25 40  9]
  [26 32 60 47 72]]]


In [ ]:
#Perform an operation to calculate the sum of all the elements along a particular axis.

np.sum(array, axis=None, dtype=None, out=None, keepdims=False)


210

In [ ]:
#Generate a random array and use broadcasting to perform an operation that adds a vector to each row of a 2D array.

import numpy as np

array_2d = np.random.randint(1, 10, size=(3, 4))

vector = np.array([1, 2, 3, 4])

result = array_2d + vector
print("Original 2D Array:")
print(array_2d)

print("\nVector to add:")
print(vector)

print("\nResulting Array after adding the vector to each row:")
print(result)


Deliverables

In [ ]:
#A Python notebook containing all of the code required for the tasks above.
#A brief (1-2 sentence) description of what each part of the assignment does.



# Importing necessary libraries
import numpy as np
import pandas as pd

# Task 1: Load the dataset and display the first 5 and last 10 rows
# Load the California housing dataset (replace with the path where it's saved if not using Google Colab)
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

# Display the first 5 rows
print("First 5 rows of the dataset:")
print(df.head())

# Display the last 10 rows
print("\nLast 10 rows of the dataset:")
print(df.tail(10))

# Task 2: Get a statistical summary of the dataset
# This provides basic statistics like mean, standard deviation, etc., for each numeric column in the dataset.
print("\nStatistical summary of the dataset:")
print(df.describe())

# Task 3: Identify unique values in the 'total_bedrooms' column and the number of distinct values
# We extract and count the distinct values in the 'total_bedrooms' column.
unique_values_total_bedrooms = df['total_bedrooms'].unique()
num_unique_total_bedrooms = len(unique_values_total_bedrooms)
print(f"\nUnique values in 'total_bedrooms': {unique_values_total_bedrooms}")
print(f"Number of distinct values in 'total_bedrooms': {num_unique_total_bedrooms}")

# Task 4: Add a new column 'total_bedrooms_per_total_rooms' calculated as 'total_bedrooms' / 'total_rooms'
# This computes the ratio of 'total_bedrooms' to 'total_rooms' and adds it as a new column to the DataFrame.
df['total_bedrooms_per_total_rooms'] = df['total_bedrooms'] / df['total_rooms']
print("\nDataset with new column 'total_bedrooms_per_total_rooms':")
print(df.head())

# Task 5: Compute mean and standard deviation of the new column 'total_bedrooms_per_total_rooms'
# This calculates and displays the mean and standard deviation of the newly created column.
mean_total_bedrooms_per_total_rooms = df['total_bedrooms_per_total_rooms'].mean()
std_total_bedrooms_per_total_rooms = df['total_bedrooms_per_total_rooms'].std()
print(f"\nMean of 'total_bedrooms_per_total_rooms': {mean_total_bedrooms_per_total_rooms}")
print(f"Standard deviation of 'total_bedrooms_per_total_rooms': {std_total_bedrooms_per_total_rooms}")

# Task 6: Filter the dataset where 'median_income' is greater than 5
# This filters the rows where 'median_income' is greater than 5.
filtered_df = df[df['median_income'] > 5]
print("\nFiltered dataset where 'median_income' > 5:")
print(filtered_df.head())

# Task 7: Create a subset where 'total_rooms' exceeds 10,000 and 'median_house_value' is below $150,000
# This creates a subset of data that satisfies both conditions: 'total_rooms' > 10,000 and 'median_house_value' < 150,000.
subset_df = df[(df['total_rooms'] > 10000) & (df['median_house_value'] < 150000)]
print("\nSubset where 'total_rooms' > 10,000 and 'median_house_value' < $150,000:")
print(subset_df.head())

# Task 8: Save the modified DataFrame (with the new column) to a new CSV file
# Saves the DataFrame with the new column 'total_bedrooms_per_total_rooms' to a new CSV file.
df.to_csv('/content/sample_data/california_housing_modified.csv', index=False)
print("\nModified DataFrame saved to 'california_housing_modified.csv'")

# Task 9: Create a 1D NumPy array of integers from 1 to 20
# Generates a 1D array of integers from 1 to 20 using np.arange.
array_1d = np.arange(1, 21)
print("\n1D NumPy array of integers from 1 to 20:")
print(array_1d)

# Task 10: Extract the even numbers from the 1D array using slicing
# Extracts even numbers from the array using slicing with a step size of 2.
even_numbers = array_1d[::2]
print("\nEven numbers from the array:")
print(even_numbers)

# Task 11: Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100
# Creates a 2D array (5x4) of random integers between 10 and 100.
array_2d = np.random.randint(10, 100, size=(5, 4))
print("\n2D array (5x4) filled with random integers between 10 and 100:")
print(array_2d)

# Task 12: Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns)
# Extracts a 3x2 subarray (first three rows, first two columns) from the 2D array.
subarray_3x2 = array_2d[:3, :2]
print("\nExtracted 3x2 subarray from the 2D array:")
print(subarray_3x2)

# Task 13: Reshape the 1D array of integers into a 4x5 2D array
# Reshapes the 1D array into a 4x5 2D array.
reshaped_array = array_1d.reshape(4, 5)
print("\nReshaped 1D array into a 4x5 2D array:")
print(reshaped_array)

# Task 14: Flatten the 2D array back to a 1D array and print it
# Flattens the reshaped 2D array back into a 1D array.
flattened_array = reshaped_array.flatten()
print("\nFlattened 2D array back to 1D:")
print(flattened_array)

# Task 15: Perform matrix multiplication between two 2D arrays (generated randomly)
# Generates two random 2D arrays and multiplies them using np.dot.
array_2d_1 = np.random.randint(1, 10, size=(3, 2))
array_2d_2 = np.random.randint(1, 10, size=(2, 4))
matrix_multiplication_result = np.dot(array_2d_1, array_2d_2)
print("\nResult of matrix multiplication between two 2D arrays:")
print(matrix_multiplication_result)

# Task 16: Create a NumPy array of 50 random integers between 0 and 100
# Generates a NumPy array of 50 random integers in the range [0, 100].
random_integers = np.random.randint(0, 101, size=50)
print("\nNumPy array of 50 random integers between 0 and 100:")
print(random_integers)

# Task 17: Use Boolean indexing to extract all values greater than 50 from the array
# Filters the array to extract all values greater than 50.
greater_than_50 = random_integers[random_integers > 50]
print("\nValues greater than 50 from the array:")
print(greater_than_50)

# Task 18: Use fancy indexing to extract elements from the array at specific indices
# Uses fancy indexing to extract elements at specified indices from the array.
indices = [2, 5, 10, 20, 30]  # Example indices
fancy_indexed_elements = random_integers[indices]
print("\nFancy indexing to extract elements at specific indices:")
print(fancy_indexed_elements)

# Task 19: For the 2D array created earlier, calculate the mean, max, and sum along each column
# Computes the mean, max, and sum of each column in the 2D array.
mean_per_column = np.mean(array_2d, axis=0)
max_per_column = np.max(array_2d, axis=0)
sum_per_column = np.sum(array_2d, axis=0)
print("\nMean per column of the 2D array:")
print(mean_per_column)
print("\nMax per column of the 2D array:")
print(max_per_column)
print("\nSum per column of the 2D array:")
print(sum_per_column)

# Task 20: Create a mask to select elements that are greater than the mean value for each column
# Creates a boolean mask and filters the array to select elements greater than the mean value in each column.
mask = array_2d > mean_per_column
filtered_array = array_2d[mask]
print("\nFiltered array with elements greater than the column means:")
print(filtered_array)

# Task 21: Print the Fibonacci sequence up to 100 using a loop
# This function prints all Fibonacci numbers up to a given limit (100 in this case).
def fibonacci_sequence(limit):
    fib_seq = []
    a, b = 0, 1
    while a <= limit:
        fib_seq.append(a)
        a, b = b, a + b
    return fib_seq

fib_seq = fibonacci_sequence(100)
print("\nFibonacci sequence up to 100:")
print(fib_seq)

# Task 22: Loop through numbers from 1 to 50 and print:
# "